---

group: stable
dist: bionic
sudo: required

language: python
python:
  - 2.7

env:
  - ANSIBLE_INSTALL_VERSION=2.9.3
  - ANSIBLE_INSTALL_VERSION=2.8.8

services:
  - docker

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -o Dpkg::Options::="--force-confold" --force-yes -y docker-ce

install:
  - make deps

script:
  - make test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
